# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Logigram' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Logigram
   pod 'RxSwift'
   pod 'R.swift'
   pod 'RxCocoa'

  target 'LogigramTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'LogigramUITests' do
    # Pods for testing
  end

end
